version: '3.8'

services:
  web:
    build: .
    container_name: web
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password_123
    ports:
      - "33060:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
